stages:
  split:
    cmd: python3 src/data/split_dataset.py
    deps:
    - data/raw_data/raw.csv
    - src/data/split_dataset.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
    params:
    - split
  data_normalization:
    cmd: python3 src/data/normalization.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/data/normalization.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  gridsearch:
    cmd: python3 src/models/gridsearch.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/models/gridsearch.py
    params:
    - rf_params
    outs:
    - models/rf_params.pkl
  model_training:
    cmd: python3 src/models/train.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - models/rf_params.pkl
    - src/models/train.py
    outs:
    - models/rf_regressor.pkl
  model_evaluation:
    cmd: python3 src/models/evaluate.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/rf_regressor.pkl
    - src/models/evaluate.py
    outs:
    - data/predictions/y_pred.csv
    metrics:
    - metrics/scores.json:
        cache: false
