split:
  test_size: 0.2
  random_state: 42
rf_params:
  n_estimators: [10, 25, 50, 100, 200]
  criterion: ["squared_error", "absolute_error", "friedman_mse"]
  max_depth: [3, 6, None]
  random_state: 42